<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use ShopBundle\Entity\CartItem;

/**
 * CartItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(CartItem::class));
    }

    /**
     * @param CartItem $cartItem
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function addCartItem(CartItem $cartItem)
    {
        $this->_em->persist($cartItem);
        $this->_em->flush($cartItem);
    }

    /**
     * @param CartItem $cartItem
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function editCartItem(CartItem $cartItem)
    {
        $this->_em->merge($cartItem);
        $this->_em->flush();
    }
}
