<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use ShopBundle\Entity\Order;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Order::class));
    }

    /**
     * @param Order $order
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function create(Order $order) {
        $this->_em->persist($order);
        $this->_em->flush($order);
    }

    /**
     * @param Order $order
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function update(Order $order)
    {
        $this->_em->merge($order);
        $this->_em->flush($order);
    }
}
