<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use ShopBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Product::class));
    }

    /**
     * @param Product $product
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function create($product)
    {
        $this->_em->persist($product);
        $this->_em->flush($product);
    }

    /**
     * @param Product $product
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function edit($product)
    {
        $this->_em->merge($product);
        $this->_em->flush($product);
    }

//    /**
//     * @param Product $product
//     * @throws \Doctrine\ORM\OptimisticLockException
//     */
//    public function delete($product)
//    {
//        $this->_em->remove($product);
//        $this->_em->flush($product);
//    }
}
